networks:
  app:
    name: "kafka-pagination"

volumes:
  kafka:
    name: "kafka-pagination"

services:
  kafka:
    image: "apache/kafka:4.1.1"
    restart: "always"
    hostname: "kafka-svc"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-svc:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      CLUSTER_ID: "kafka-pagination"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    volumes:
      - "kafka:/var/lib/kafka/data"
    ports:
      - "9092:9092"
    networks:
      - "app"

#   https://ui.docs.kafbat.io/configuration/misc-configuration-properties
  kafbat:
    image: "kafbat/kafka-ui:main"
    restart: "always"
    hostname: "kafbat-svc"
    depends_on:
      - "kafka"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "Cluster-1"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-svc:9092"
    ports:
      - "8001:8080"
    networks:
      - "app"

